### ISSUE TITLE
Use 64bit version of Ableton Live

### ISSUE THREAD

**Issue by willits** [EnvelopSound/EnvelopLive#6]
When running Ableton Live 9.6.1 in 32bit mode M4L device will not open. 
Live 9.6.1 64bit works great.

**Comment by cameronangeli** [comment]
Hey team,

We've made some great updates to the client and server - which we're using for a custom setup at music Savages camp this year at burning man. 

We're hoping to have a two hour envelop set each day out there. Are any of you planning to attend Bman this year? 



Cameron Angeli | c: 310-502-9447 | o: 424-204-4064

**Comment by roddylindsay** [comment]
@willits I just downloaded latest version of Live (9.6.2) and I was able to open envelop stereo, envelop mono, and global reverb just fine.  Can you send a screenshot or a more detailed error message?

**Comment by willits** [comment]
9.6.2 32bit or 64?

64 works. 32 giving errors. 

Christopher


christopherwillits.com
overlap.org
envelop.us

**Comment by willits** [comment]
<img width="1440" alt="screenshot 2016-08-21 15 35 11" src="https://cloud.githubusercontent.com/assets/15992967/17840229/fdce3338-67b4-11e6-97a1-0e835ab5c9a1.png">

**Comment by ramagottfried** [comment]
it's possible that the alex harker extension objects are only built for 64bit, I'll check on that, thanks.

**Comment by ramagottfried** [comment]
actually this is because you were running 64bit Max, you can change this by setting Max to open in 32bit mode (select the Max.app, and hit cmd-i to open the inspector, and then select "open in 32bit mode").

this is only an issue if you are trying to edit the devices.

**Comment by willits** [comment]
Thanks!

64bit Max is the default when installed or upgraded.
Let's make sure we document this clearly for potential editors.

Ideal would have everything editable in 64bit Max. Why is that not possible?

Christopher


christopherwillits.com
drip.kickstarter.com/willits
envelop.us
overlap.org

**Comment by ramagottfried** [comment]
no problem!  either way is possible, it's just that your Live and Max applications need to be running with the same bit mode.

**Comment by willits** [comment]
Got it. Great documentation note here. 

Max 7.2.5 actually defaults to 32bit I'm seeing. 

Christopher


christopherwillits.com
drip.kickstarter.com/willits
envelop.us
overlap.org
